### ISSUE TITLE
Scope of project

### ISSUE THREAD

**Issue by operezfuentes** [mdoi/fluent-plugin-gcloud-pubsub#1]
Hi,
I'm interested in use a Fluent out plugin for Google pub sub.

Searching in github I find 2 plugins:
- https://github.com/mdoi/fluent-plugin-gcloud-pubsub
- https://github.com/shojikai/fluent-plugin-google-cloud-pubsub

Please, can you indicate what is the scope of this plugin and motivations to do not use shojika plugin. (Any differences?)

Thanks!

**Comment by mdoi** [comment]
@operezfuentes 
Hi
I wanted input plugin. So I developed plugin and made the code more simplify with [gcloud gem](https://googlecloudplatform.github.io/gcloud-ruby/).
